Bugtracker1/bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
]

Bugtracker1/mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'
urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('signup/',views.signupPage,name='sign-up'),


    path('mybugs/',views.mybugs,name='mybugs'),
    path('assignedBugs/',views.assignedBugs,name='assigned-bugs'),
    path('raisebug/',views.raiseBug,name='raisebug'),
    path('bug/<slug:pk>/edit/',views.BugUpdateView.as_view(),name='bug_edit'),
    path('bug/<slug:pk>/',views.BugDetail,name='bug_detail'),
    path('bug/<slug:pk>/remove/',views.BugDeleteView.as_view(),name='bug_remove'),
]

Bugtracker1/mysite/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class UserProfileInfo(models.Model):
    ROLE = (
        ('OL', 'Organisation-Lead'),
        ('SDE1', 'SeniorDeveloper'),
        ('SDE2', 'JuniorDeveloper'),
        ('U', 'User'),
    )
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    # additional
    role = models.CharField(max_length=4, choices=ROLE, default='U')
    def __str__(self):
        return self.user.username 

class Bug(models.Model):
    SEVERITY_LEVEL = (
        ('H', 'High'),
        ('M', 'Medium'),
        ('L', 'Low'),
        ('NS', 'Not Yet Set'),
    )
    title = models.CharField(max_length=400)
    description = models.TextField(blank=True)
    severity_level = models.CharField(max_length=4, choices=SEVERITY_LEVEL,default='NS')
    resolved = models.BooleanField(default=False)
    assigned_to = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,related_name='assignedperson',null=True)
    deadline = models.DateTimeField(default=datetime.now())
    raised_by = models.CharField(max_length=150,blank=True,null=True)
    visibility = models.IntegerField(default=1)
    resolved_on = models.DateTimeField(default=datetime.now(), blank=True)
    opened_on = models.DateTimeField(default=timezone.now)
    assigned_on = models.DateTimeField(default=datetime.now(), blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("mysite:bug_detail", kwargs={"pk": self.pk})
    

class Comment(models.Model):
    bug = models.ForeignKey(Bug,related_name='bug',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("mysite:bug_detail")
    

    def __str__(self):
        return self.text

Bugtracker1/mysite/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from mysite.models import Bug
from mysite.models import UserProfileInfo, Comment



# class UserProfileInfoForm(forms.ModelForm):
#     class Meta():
#         model = UserProfileInfo
#         fields = ['username','email','password1','password2','position']

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields =['username','email','password',]

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ['role',]

class RaiseBugForm(forms.ModelForm):
    class Meta():
        model = Bug
        fields = ['title', 'description',]

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ['text',]

Bugtracker1/mysite/views.py
from datetime import date, timezone, datetime
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from mysite.forms import RaiseBugForm
from mysite.forms import UserProfileInfoForm, UserForm, CommentForm
from mysite.models import UserProfileInfo, Bug, Comment
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def index(request):
    if(not request.user.is_authenticated):
        bugs = Bug.objects.filter(resolved=True, visibility=1).order_by('-resolved_on')
        
    else:
        user = UserProfileInfo.objects.get(user=request.user)
        if(user.role == 'U' or user.role == 'SDE2'):
            bugs = Bug.objects.filter(resolved=True, visibility=1).order_by('-resolved_on')
        else:
            bugs = Bug.objects.filter(resolved=True).order_by('-resolved_on')
    
    return render(request, 'mysite/index.html',{
            'bugs' : bugs,
    })

@login_required(login_url='/login')
def assignedBugs(request):
    if(not request.user.is_authenticated ):
        return HttpResponse("You are not allowed to view this page!")
    else:
        user = UserProfileInfo.objects.get(user=request.user)
        if(user.role == 'U'):
            user = UserProfileInfo.objects.get(user=request.user)
        else:
            bugs = Bug.objects.filter(assigned_to=user.user).order_by('-assigned_on')
    
    return render(request, 'mysite/assigned_bugs.html',{
            'bugs' : bugs,
    })


@login_required(login_url='/login')
def mybugs(request):
    user = request.user
    bugs = Bug.objects.filter(raised_by=user).order_by('-opened_on')
    return render(request, 'mysite/mybugs.html',{
            'bugs' : bugs,
    })

def loginPage(request):
    if (request.method =='POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('mysite:index')
        else:
            messages.info(request, 'Username OR Password is incorrect')
            return render(request, 'mysite/login.html')
    return render(request,'mysite/login.html')   

# @login_required
def logoutUser(request):
    logout(request)
    return redirect('mysite:index')

def signupPage(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        # profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() :

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # profile = profile_form.save(commit=False)
            # profile.user = user

            # profile.save()
            return redirect('mysite:login')
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
        # profile_form = UserProfileInfoForm()
 
    return render(request,'mysite/signup.html',{'user_form':user_form,})

@login_required(login_url='login/')
def raiseBug(request):
    form = RaiseBugForm()

    if request.method == "POST":
        username = request.user.username
        print(username)
        form = RaiseBugForm(
            data=request.POST,
        )
        form= form.save()
        user = User.objects.filter(username=username)
        form.raised_by=username
        form.save()
        return redirect('mysite:bug_detail', pk=form.pk)
    return render(request, 'mysite/bug_form.html',{
        'form':form,
    })

class BugUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'mysite/bug_form.html'
    form_class = RaiseBugForm
    model = Bug

def BugDetail(request,pk):
    bug = Bug.objects.get(pk=pk)
    comment_form = CommentForm()
    if request.method == "POST":
        username = request.user.username
        print(username)
        form = CommentForm(
            data=request.POST,
        )
        form= form.save()
        user = User.objects.filter(username=username)
        form.author=username
        form.save()
        return redirect('mysite:bug_detail', pk=pk)
    return render(request, 'mysite/bug_detail.html',{
        'comment_form':comment_form,
        'object':bug,
    })



class BugDeleteView(LoginRequiredMixin,DeleteView):
    model = Bug
    success_url = reverse_lazy('mysite:mybugs') 

Bugtracker1/mysite/templates/mysite/assigned_bugs.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    {% comment %} <link rel="stylesheet" href="{% static 'mysite/css/style.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'mysite/css/home_style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div id="nav-bar">
        <ul class="left nav-bar-options">
            {% if request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:index' %}">Home</a></li>
            <li><a class="link" href="{% url 'mysite:mybugs' %}">My Bugs</a></li>
            {% comment %} <li><a class="link" href="{% url 'mysite:assigned-bugs' %}">Assigned Bugs</a></li> {% endcomment %}
            {% endif %}
        </ul>
        <ul class="right nav-bar-options">
            {% if not request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:login' %}">Log In</a></li>
            {% else %}
            <li><a class="link" href="{% url 'mysite:logout' %}">Log Out</a></li>
            {% endif %}
        </ul>
    </div>
    {% if request.user.is_authenticated %}">
        <a href="{% url 'mysite:raisebug' %}" class="add-button">+</a>
        
    {% endif %}
    <div id="bug-list">
        {% for bug in bugs %}
        <div id="high-sample-tile" class="tile">
            <div class="tile-header">
                <a href="{{bug.get_absolute_url}}"><h2 class="bug-title">{{bug.title}}</h2></a>
                {% if bug.severity_level == 'H' %}
                <span class="H severity">High</span>
                {% elif bug.severity_level == 'M' %}
                <span class="M severity">Medium</span>
                {% else %}
                <span class="L severity">Low</span>
                {% endif %}
                {% if bug.resolved %}
                <span class="resolved status">resolved</span>
                {% else %}
                <span class="unresolved status">unresolved</span>
                {% endif %}
            </div>
            <div class="assigned">Assigned To: {{bug.assigned_to}}</div>
            <div class="deadline">Raised By: {{bug.raised_by}}</div>
            <div class="deadline">Resolve By: {{bug.deadline}}</div>
        </div>
        {% endfor %}
        
    </div>
    
</body>
</html>
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>This is assigned bugs page!</h1>
        {% if not request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mysite:sign-up' %}">Sign-Up</a>
        <a class="btn btn-primary" href="{% url 'mysite:login' %}">Log In</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'mysite:logout' %}">Logout</a>
        <a class="btn btn-primary" href="{% url 'mysite:mybugs' %}">My Bugs</a>
        {% endif %}

        {% for bug in bugs %}
            <h1><a href="">{{bug.title}}</a></h1>
            <p>Severity level: {{bug.severity_level}}</p>
            <p>Resolved or not: {{bug.resolved}}</p>
            <p>Deadline: {{bug.deadline}}</p>
            <p>Assigned To: {{bug.assigned_to}}</p>
            <p>Raised To: {{bug.raised_by}}</p>
        {% endfor %}
    </div>
</body>
</html>
 {% endcomment %}

Bugtracker1/mysite/templates/mysite/bug_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ object }}</p>
            <input type="submit" value="Confirm" class="btn btn-danger">
        </form>
    </div>
</body>
</html>

Bugtracker1/mysite/templates/mysite/bug_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raise a bug</title>
    <link rel="stylesheet" href="{% static 'mysite/css/home_style.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/css/form_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
</head>
<body>
    <div id="nav-bar">
        <ul class="left nav-bar-options">
            {% if request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:index' %}">Home</a></li>
            <li><a class="link" href="{% url 'mysite:mybugs' %}">My Bugs</a></li>
            {% comment %} <li><a class="link" href="{% url 'mysite:assigned-bugs' %}">Assigned Bugs</a></li> {% endcomment %}
            {% endif %}
        </ul>
        <ul class="right nav-bar-options">
            {% if not request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:login' %}">Log In</a></li>
            {% else %}
            <li><a class="link" href="{% url 'mysite:logout' %}">Log Out</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="form-container">
        <h2 class="form-title">Raise a Bug</h2>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="submit" value="Raise the Bug">Raise the error</button>
            </form>
        </div>
        <div class="footer">Made by WebWizards</div>
        
        <script>
            var form_fields = document.getElementsByTagName('input')
            form_fields[1].type='text';
            form_fields[2].type='text';
            form_fields[2].className +='desc';
        </script>
    </body>
    </html>
    
    {% comment %} <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Raise a Bug</title>
    </head>
    <body>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <input type="submit" name="" value="Raise the Bug">
        </form>
    </body>
    </html> {% endcomment %}

Bugtracker1/mysite/templates/mysite/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'mysite/css/home_style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div id="nav-bar">
        <ul class="left nav-bar-options">
            {% if request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:index' %}">Home</a></li>
            <li><a class="link" href="{% url 'mysite:mybugs' %}">My Bugs</a></li>
            <li><a class="link" href="{% url 'mysite:assigned-bugs' %}">Assigned Bugs</a></li>
            {% endif %}
        </ul>
        <ul class="right nav-bar-options">
            {% if not request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:login' %}">Log In</a></li>
            {% else %}
            <li><a class="link" href="{% url 'mysite:logout' %}">Log Out</a></li>
            {% endif %}
        </ul>
    </div>
    {% if request.user.is_authenticated %}">
        <a href="{% url 'mysite:raisebug' %}" class="add-button">+</a>
        
    {% endif %}
    <div id="bug-list">
        
        {% for bug in bugs %}
        <div id="high-sample-tile" class="tile">
            <div class="tile-header">
                <a href="{{bug.get_absolute_url}}"><h2 class="bug-title">{{bug.title}}</h2></a>
                {% if bug.severity_level == 'H' %}
                <span class="H severity">High</span>
                {% elif bug.severity_level == 'M' %}
                <span class="M severity">Medium</span>
                {% else %}
                <span class="L severity">Low</span>
                {% endif %}
                {% if bug.resolved %}
                <span class="resolved status">resolved</span>
                {% else %}
                <span class="unresolved status">unresolved</span>
                {% endif %}
            </div>
            <div class="assigned">Assigned To: {{bug.assigned_to}}</div>
            <div class="deadline">Raised By: {{bug.raised_by}}</div>
            <div class="deadline">Resolve By: {{bug.deadline}}</div>
        </div>
        {% endfor %}
        
    </div>
    
</body>
</html>


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>This is index page!</h1>
        {% if not request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mysite:sign-up' %}">Sign-Up</a>
        <a class="btn btn-primary" href="{% url 'mysite:login' %}">Log In</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'mysite:logout' %}">Logout</a>
        <a class="btn btn-primary" href="{% url 'mysite:mybugs' %}">My Bugs</a>
        <a class="btn btn-primary" href="{% url 'mysite:assigned-bugs' %}">Assigned Bugs</a>
        {% endif %}

        {% for bug in bugs %}
            <h1><a href="">{{bug.title}}</a></h1>
            <p>Severity level: {{bug.severity_level}}</p>
            <p>Resolved or not: {{bug.resolved}}</p>
            <p>Deadline: {{bug.deadline}}</p>
            <p>Assigned To: {{bug.assigned_to}}</p>
            <p>Raised To: {{bug.raised_by}}</p>
        {% endfor %}
    </div>
</body>
</html> {% endcomment %}

Bugtracker1/mysite/templates/mysite/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>Login</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'mysite/css/loginstyle.css' %}"
    />
  </head>
  <body>
    <div class="loginbox">
      <img src="{% static 'mysite/images/avatar.jpg' %}" class="avatar" />
      <h1>LOGIN HERE!</h1>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p>username</p>
        <input type="text" name="username" placeholder="ENTER USERNAME" />
        <p>password</p>
        <input type="password" name="password" placeholder="ENTER password" />
        <input type="submit" value="login" />
        <a href="{% url 'mysite:sign-up' %}"> SIGN UP</a>
      </form>
    </div>
  </body>
</html>

Bugtracker1/mysite/templates/mysite/mybugs.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    {% comment %} <link rel="stylesheet" href="{% static 'mysite/css/style.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'mysite/css/home_style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div id="nav-bar">
        <ul class="left nav-bar-options">
            {% if request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:index' %}">Home</a></li>
            {% comment %} <li><a class="link" href="{% url 'mysite:mybugs' %}">My Bugs</a></li> {% endcomment %}
            <li><a class="link" href="{% url 'mysite:assigned-bugs' %}">Assigned Bugs</a></li>
            {% endif %}
        </ul>
        <ul class="right nav-bar-options">
            {% if not request.user.is_authenticated %}
            <li><a class="link" href="{% url 'mysite:login' %}">Log In</a></li>
            {% else %}
            <li><a class="link" href="{% url 'mysite:logout' %}">Log Out</a></li>
            {% endif %}
        </ul>
    </div>
    {% if request.user.is_authenticated %}">
        <a href="{% url 'mysite:raisebug' %}" class="add-button">+</a>
        
    {% endif %}
    <div id="bug-list">
        
        {% for bug in bugs %}
        <div id="high-sample-tile" class="tile">
            <div class="tile-header">
                <a href="{{bug.get_absolute_url}}"><h2 class="bug-title">{{bug.title}}</h2></a>
                {% if bug.severity_level == 'H' %}
                <span class="H severity">High</span>
                {% elif bug.severity_level == 'M' %}
                <span class="M severity">Medium</span>
                {% else %}
                <span class="L severity">Low</span>
                {% endif %}
                {% if bug.resolved %}
                <span class="resolved status">resolved</span>
                {% else %}
                <span class="unresolved status">unresolved</span>
                {% endif %}
            </div>
            <div class="assigned">Assigned To: {{bug.assigned_to}}</div>
            <div class="deadline">Raised By: {{bug.raised_by}}</div>
            <div class="deadline">Resolve By: {{bug.deadline}}</div>
        </div>
        {% endfor %}
        
    </div>
    
</body>
</html>
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Bugs</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


</head>
<body>
    <div class="container">

        <h1>This is my bugs page!</h1>
        {% if not request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mysite:sign-up' %}">Sign-Up</a>
        <a class="btn btn-primary" href="{% url 'mysite:login' %}">Log In</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'mysite:logout' %}">Logout</a>
        {% endif %}

        <a href="{% url 'mysite:raisebug' %}" class="btn btn-primary">Raise a bug</a>

        {% for bug in bugs %}
            <h1><a href="{{bug.get_absolute_url}}">{{bug.title}}</a></h1>
            <p>Severity level: {{bug.severity_level}}</p>
            <p>Resolved or not: {{bug.resolved}}</p>
            <p>Deadline: {{bug.deadline}}</p>
            <p>Assigned To: {{bug.assigned_to}}</p>
            <p>Raised To: {{bug.raised_by}}</p>
            <a href="{% url 'mysite:bug_remove' pk=bug.pk %}" class="btn btn-primary">Edit</a>

        {% endfor %}
    </div>
</body>
</html> {% endcomment %}

Bugtracker1/mysite/templates/mysite/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Sign-Up</title>
  <link rel="stylesheet" type="text/css" href="{% static 'mysite/css/loginstyle.css' %}" />
</head>
<body>
    <div class="signupbox">
      <img src="avatar.jpg" class="avatar" />
      <h1>SIGNUP HERE!</h1>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p>Username</p>
        {% comment %} <input type="text" name="" placeholder="ENTER USERNAME" /> {% endcomment %}
        {{user_form.username}}
        <p>Email-Id</p>
        {% comment %} <input type="email" name="" placeholder="ENTER EMAIL" /> {% endcomment %}
        {{user_form.email}}
        <p>Password</p>
        {% comment %} <input type="password" name="" placeholder="ENTER password" /> {% endcomment %}
        {{user_form.password}}
        </form>
        <input type="submit" value="Sign-Up">
      </form>
      {{form.errors}}
      <a href="{% url 'mysite:login' %}">Back to login</a>
    </div>


    <script>

        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='ENTER USERNAME';
        form_fields[2].placeholder='name@example.com';
        form_fields[3].placeholder='Password';
        form_fields[1].type='text';
        form_fields[2].type='email';
        form_fields[3].type='password';

    </script>
  </body>